import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../Components/header";
import Footer from "../Components/footer";
import { MiembroProvider } from "@/Provider/provider";
import { SessionProvider } from "@/Provider/loginProvider";
import SessionManager from "@/Components/session/sessionManager";
import { ThemeProvider } from "@/Provider/ThemeProvider";
import QueryProvider from "@/Provider/TanStackProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Visoft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <QueryProvider>
            <MiembroProvider>
              <SessionProvider>
                <SessionManager />
                {children}
              </SessionProvider>
            </MiembroProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
