// RootLayout.jsx (actualizado)
import { Inter } from "next/font/google"; 
import "./globals.css"; 
import { MiembroProvider } from "@/Provider/provider"; 
import { SessionProvider } from "@/Provider/loginProvider"; 
import SessionManager from "@/Components/session/sessionManager"; 
import { ThemeProvider } from "@/Provider/ThemeProvider"; 
import ClientLayout from './clientLayout'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Visoft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <MiembroProvider>
            <SessionProvider>
              <SessionManager>
              <ClientLayout>
                {children}
              </ClientLayout>
              </SessionManager>
            </SessionProvider>
          </MiembroProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
